version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=SSO Test
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=adminpassword
    volumes:
      - ./openldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif:z
    ports:
      - "389:389"
    networks:
      - sso_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HOSTNAME_STRICT=false
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import:z
    ports:
      - "8080:8080"
    networks:
      - sso_network
    depends_on:
      - openldap

  step-ca:
    image: smallstep/step-ca:0.26.1
    container_name: step-ca
    environment:
      - DOCKER_STEPCA_INIT_NAME=SSO Test CA
      - DOCKER_STEPCA_INIT_DNS=step-ca,localhost
      - DOCKER_STEPCA_INIT_ADDRESS=:9000
      - DOCKER_STEPCA_INIT_PROVISIONER=admin
      - DOCKER_STEPCA_INIT_CA_PASSWORD_FILE=/home/step/secrets/password
      - DOCKER_STEPCA_INIT_PROVISIONER_PASSWORD_FILE=/home/step/secrets/password
      - DOCKER_STEPCA_INIT_ADMIN_PROVISIONER=admin
      - DOCKER_STEPCA_INIT_ADMIN_SUBJECT=admin
      - STEPPATH=/home/step
    ports:
      - "9000:9000"
    volumes:
      # Wir verwenden nur noch Bind Mounts mit dem SELinux/AppArmor Flag `:z`
      - ./step-ca/config:/home/step/config:z
      - ./step-ca/secrets:/home/step/secrets:z
      - ./step-ca/db:/home/step/db:z
      - ./step-ca/certs:/home/step/certs:z
    networks:
      - sso_network
    depends_on:
      - keycloak

  sshd-server:
    build:
      context: ./sshd-server
      # Dockerfile im Kontext reicht aus
    container_name: sshd-server
    ports:
      - "2222:22"
    volumes:
      # Wir mounten das certs-Verzeichnis, damit das Start-Skript die CA kopieren kann
      - ./step-ca/certs:/step-ca-certs:ro,z
    networks:
      - sso_network
    depends_on:
      - step-ca

  test-client:
    image: smallstep/step-cli:0.26.1
    container_name: test-client
    command: sleep infinity
    networks:
      - sso_network
    volumes:
      # Auch hier zur Sicherheit der Flag
      - ./step-cli-data:/home/step:z
    depends_on:
      - sshd-server

networks:
  sso_network:
    driver: bridge

# Wir verwenden keine benannten Volumes mehr, um Berechtigungsprobleme zu vermeiden
